setTimeout(() => {
  try {
    console.log('try' + fe);
  } catch (err) {
    console.log('catch: ', err);
  }
}, 500);
